version: "3"

volumes:
  db-data:

services:
  choboi:
    build: .
    environment:
      SLACK_CHOBOI_API_TOKEN: ${SLACK_CHOBOI_API_TOKEN}
    volumes:
      - ./:/usr/src/app:z
    depends_on:
      - db

  migrate:
    build: .
    command: alembic upgrade head
    volumes:
      - ./:/usr/src/app:z
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: choboi
      POSTGRES_PASSWORD: choboi
      PGDATA: /var/lib/posgresql/data/db-data
    volumes:
      - "db-data:/var/lib/posgresql/data/db-data:z"
    ports:
      - 55432:5432

  adminer:
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - 55433:8080
