version: '3'

volumes:
  db-data:

services:
  choboi:
    build: .
    environment:
      SLACK_CHOBOI_API_TOKEN: ${SLACK_CHOBOI_API_TOKEN}
    depends_on:
      - db

  migrate:
    build: .
    command: alembic upgrade head
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    environment:
      POSTGRES_USER: choboi
      POSTGRES_PASSWORD: choboi
      PGDATA: /var/lib/posgresql/data/db-data
    volumes:
      - 'db-data:/var/lib/posgresql/data/db-data:z'
    ports:
      - 55432:5432
